apiVersion: batch/v1
kind: Job
metadata:
  name: openshift-service-catalog-controller-manager-remover
  namespace: openshift-service-catalog-removed
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
spec:
  template:
    spec:
      serviceAccountName: openshift-service-catalog-controller-manager-remover
      containers:
      - name: openshift-service-catalog-controller-manager-remover
        securityContext: {}
        # image will be some registry image
        image: registry.svc.ci.openshift.org/openshift/origin-v4.0:cluster-svcat-controller-manager-operator
        command: ["/usr/bin/cluster-svcat-controller-manager-remover"]
        resources:
          requests:
            memory: 50Mi
      restartPolicy: Never
  backoffLimit: 4
