apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-service-catalog-removed
  name: openshift-service-catalog-controller-manager-remover
  labels:
    app: openshift-service-catalog-controller-manager-remover
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
